server:
  port: 9095

#enabling the H2 console
spring.h2.console.enabled: true

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:cart
    username: sa
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true


  application:
    name: CART-SERVICE

spring.mvc.pathmatch.matching-strategy : ANT_PATH_MATCHER


