server:
  port: 9094

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderhistory
    username: root
    password: Shalini@$2802
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true



  application:
    name: ORDER-SERVICE

spring.mvc.pathmatch.matching-strategy : ANT_PATH_MATCHER

